import json
from argparse import ArgumentParser, Namespace

import matplotlib.pyplot as plt
from huggingface_hub import HfApi


def parseArgs() -> Namespace:
    parser: ArgumentParser = ArgumentParser(
        prog="Hugging Face Model Downloads Plotter",
        usage="Plot model download data on a logarithmic scale",
    )
    parser.add_argument(
        "-i",
        "--input",
        type=str,
        default="modelDownloads.json",
        help="A JSON file containing the number of downloads per model generated by Hugging Face Model Download Extractor",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=str,
        default="modelDownloads.pdf",
        help="Filename to save plot to",
    )
    parser.add_argument(
        "--no-negatives",
        action="store_true",
        default=False,
        help="Flag to not plot models with -1 downloads (e.g. prohibited access models)",
    )
    return parser.parse_args()


def main() -> None:
    args: Namespace = parseArgs()

    with open(args.input, "r") as file:
        downloads = json.load(fp=file)
        file.close()

    if args.no_negatives:
        downloads = [d for d in downloads if d != -1]

    fig, ax = plt.subplots()
    ax.set(
        title=f"Huggingface Model Downloads (total={len(downloads)})",
        xlabel="Downloads",
        ylabel="Frequency",
    )

    if not args.no_negatives:
        ax.hist(
            [0 for d in downloads if d == -1], color="orange", label="access disabled"
        )
    downloads = [d for d in downloads if d != -1]

    ax.hist(downloads, color="blue", bins=10000, label="public")

    ax.set_yscale("log")

    plt.legend()
    plt.savefig(args.output)


if __name__ == "__main__":
    main()
